server:
    port: 8020
spring:
    datasource:
        password: Profeta2
        url: jdbc:postgresql://localhost:5432/project_scrum
        username: postgres
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER

    jpa:
        database: postgresql
        generate-ddl: true
        hibernate:
            ddl-auto: create
        open-in-view: false

        properties:
            hibernate:
                enable_lazy_load_no_trans: true